var
BUGNUMBER
=
1202134
;
var
summary
=
"
Return
value
should
not
be
overwritten
by
finally
block
with
normal
execution
.
"
;
print
(
BUGNUMBER
+
"
:
"
+
summary
)
;
var
f
;
f
=
function
(
)
{
try
{
return
42
;
}
finally
{
}
}
;
assert
.
sameValue
(
f
(
)
42
)
;
f
=
function
(
)
{
try
{
return
42
;
}
finally
{
return
43
;
}
}
;
assert
.
sameValue
(
f
(
)
43
)
;
f
=
function
(
)
{
try
{
return
42
;
}
finally
{
throw
43
;
}
}
;
var
caught
=
false
;
try
{
f
(
)
;
}
catch
(
e
)
{
assert
.
sameValue
(
e
43
)
;
caught
=
true
;
}
assert
.
sameValue
(
caught
true
)
;
f
=
function
(
)
{
do
try
{
return
42
;
}
finally
{
break
;
}
while
(
false
)
;
return
43
;
}
;
assert
.
sameValue
(
f
(
)
43
)
;
f
=
function
(
)
{
L
:
try
{
return
42
;
}
finally
{
break
L
;
}
return
43
;
}
;
assert
.
sameValue
(
f
(
)
43
)
;
f
=
function
(
)
{
do
try
{
return
42
;
}
finally
{
continue
;
}
while
(
false
)
;
return
43
;
}
;
assert
.
sameValue
(
f
(
)
43
)
;
f
=
function
(
)
{
try
{
return
42
;
}
finally
{
do
try
{
return
43
;
}
finally
{
break
;
}
while
(
0
)
;
}
}
;
assert
.
sameValue
(
f
(
)
42
)
;
f
=
function
(
)
{
try
{
return
42
;
}
finally
{
L
:
try
{
return
43
;
}
finally
{
break
L
;
}
}
}
assert
.
sameValue
(
f
(
)
42
)
;
f
=
function
(
)
{
try
{
return
42
;
}
finally
{
do
try
{
return
43
;
}
finally
{
continue
;
}
while
(
0
)
;
}
}
;
assert
.
sameValue
(
f
(
)
42
)
;
f
=
function
(
)
{
try
{
return
42
;
}
finally
{
try
{
try
{
return
43
;
}
finally
{
throw
9
;
}
}
catch
(
e
)
{
}
}
}
;
assert
.
sameValue
(
f
(
)
42
)
;
f
=
function
(
)
{
try
{
return
41
;
}
finally
{
try
{
return
42
;
}
finally
{
do
try
{
return
43
;
}
finally
{
break
;
}
while
(
0
)
;
}
}
}
;
assert
.
sameValue
(
f
(
)
42
)
;
reportCompare
(
0
0
)
;
