class
ThrowingIterator
extends
Iterator
{
next
(
)
{
throw
new
Test262Error
(
)
;
}
}
let
iterator
=
new
ThrowingIterator
(
)
.
take
(
0
)
;
iterator
.
next
(
)
;
iterator
=
new
ThrowingIterator
(
)
.
take
(
1
)
;
assert
.
throws
(
Test262Error
function
(
)
{
iterator
.
next
(
)
;
}
)
;
reportCompare
(
0
0
)
;
