const
obj
=
{
toString
(
)
{
throw
'
custom
error
'
;
}
}
;
async
function
*
f
(
)
{
await
import
.
source
(
obj
)
;
}
f
(
)
.
next
(
)
.
catch
(
error
=
>
{
assert
.
sameValue
(
error
'
custom
error
'
)
;
}
)
.
then
(
DONE
DONE
)
;
