var
error
=
new
Test262Error
(
)
;
Object
.
defineProperty
(
Promise
'
resolve
'
{
get
:
function
(
)
{
throw
error
;
}
}
)
;
Promise
.
race
(
[
new
Promise
(
function
(
)
{
}
)
]
)
.
then
(
function
(
)
{
throw
new
Test262Error
(
'
The
promise
should
be
rejected
'
)
;
}
function
(
reason
)
{
assert
.
sameValue
(
reason
error
)
;
}
)
.
then
(
DONE
DONE
)
;
