asyncTest
(
async
function
(
)
{
const
expectedValue
=
{
}
;
const
inputThenable
=
{
then
(
resolve
reject
)
{
resolve
(
expectedValue
)
;
}
}
;
const
input
=
{
length
:
1
0
:
inputThenable
}
;
const
outputPromise
=
Array
.
fromAsync
(
input
v
=
>
{
throw
new
Test262Error
;
}
)
;
await
assert
.
throwsAsync
(
Test262Error
(
)
=
>
outputPromise
)
;
}
)
;
