var
ranCatch
=
false
;
try
{
throw
[
7
8
9
]
;
}
catch
(
[
.
.
.
{
0
:
v
1
:
w
2
:
x
3
:
y
length
:
z
}
]
)
{
assert
.
sameValue
(
v
7
)
;
assert
.
sameValue
(
w
8
)
;
assert
.
sameValue
(
x
9
)
;
assert
.
sameValue
(
y
undefined
)
;
assert
.
sameValue
(
z
3
)
;
assert
.
throws
(
ReferenceError
function
(
)
{
length
;
}
)
;
ranCatch
=
true
;
}
assert
(
ranCatch
'
executed
catch
block
'
)
;
reportCompare
(
0
0
)
;
