try
{
MAX_VALUE
in
Number
;
throw
new
Test262Error
(
'
#
1
.
1
:
MAX_VALUE
in
Number
throw
ReferenceError
.
Actual
:
'
+
(
MAX_VALUE
in
Number
)
)
;
}
catch
(
e
)
{
if
(
(
e
instanceof
ReferenceError
)
!
=
=
true
)
{
throw
new
Test262Error
(
'
#
1
.
2
:
MAX_VALUE
in
Number
throw
ReferenceError
.
Actual
:
'
+
(
e
)
)
;
}
}
reportCompare
(
0
0
)
;
